version: 0.2
phases:
  install:
    commands:
      - echo "In Install"
  pre_build:
    commands:
      - echo "In Pre_build"
  build:
    commands:
      - echo "Build"
      - sh ci-cd/build.sh "$Environment"